/**
 * Códigos de erro estáveis, pensados para consumo por máquina (frontend e testes).
 * Mensagens podem mudar; códigos não.
 */
export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_INACTIVE: 'USER_INACTIVE',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  CANNOT_DEACTIVATE_SELF: 'CANNOT_DEACTIVATE_SELF',
  CATEGORY_EXISTS: 'CATEGORY_EXISTS',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  INVALID_SCOPE: 'INVALID_SCOPE',
  INVALID_LESSON_ORDER: 'INVALID_LESSON_ORDER',

  COURSE_NOT_EDITABLE: 'COURSE_NOT_EDITABLE',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  COURSE_WITHOUT_LESSONS: 'COURSE_WITHOUT_LESSONS',
  CAPACITY_BELOW_ENROLLED: 'CAPACITY_BELOW_ENROLLED',
  COURSE_HAS_ENROLLMENTS: 'COURSE_HAS_ENROLLMENTS',
  LAST_LESSON_OF_PUBLISHED_COURSE: 'LAST_LESSON_OF_PUBLISHED_COURSE',

  COURSE_NOT_OPEN: 'COURSE_NOT_OPEN',
  ALREADY_ENROLLED: 'ALREADY_ENROLLED',
  COURSE_FULL: 'COURSE_FULL',
  ENROLLMENT_NOT_ACTIVE: 'ENROLLMENT_NOT_ACTIVE',
  ENROLLMENT_HAS_GRADES: 'ENROLLMENT_HAS_GRADES',
  ASSESSMENT_EXISTS: 'ASSESSMENT_EXISTS',
  GRADES_LOCKED: 'GRADES_LOCKED',
  NOT_APPROVED: 'NOT_APPROVED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
